#!/usr/bin/env bash

# Search and open bookmarks stored in local text files.

# $DATA_DIR not compatible with GNOME keyboard shortcuts
bkmk_dir="$HOME/docs/data/bkmk"
bkmk_file="$bkmk_dir/bookmarks.tsv"
bkmk_yt_file="$bkmk_dir/bookmarks-yt.tsv"
bkmk_channels_file="$bkmk_dir/channels"

if [[ $2 == "y" ]]; then
	file="$bkmk_yt_file"
else
	file="$bkmk_file"
fi

case $1 in
	"c")
		while IFS= read -r url; do
			firefox --new-tab "$url"
		done < "$bkmk_channels_file"
		;;
	"e")
		(nvim "$file" + "+set ts=60" "+set nowrap")
		;;
	"n")
		(nvim "$file" + "+normal o" "+normal pa	" "+startinsert!")
		;;
	"o")
		bookmark_number="$(awk -F "\t" '{printf "%-54.52s %-66s %-30s %s\n", $1, $2, $3, $4}' "$file" \
			| nl \
			| fzf --exact --style=full --no-preview \
			| cut --fields=1)"
		url=$(cat -n "$file" | grep ^"$bookmark_number" | cut --fields=2)
		[[ -z $bookmark_number ]] || firefox --new-tab "$url"
		;;
esac
