#!/usr/bin/env bash

# Keep track of non-periodic tasks

data_file="$CHORES_DATA_DIR/chores.tsv"

case $1 in
	"e") (cd $CHORES_DATA_DIR && nvim -c FZF $data_file +) ;;
	*) grep --ignore-case --color=auto "${*}" $data_file ;;
esac
