#!/usr/bin/env bash

# Create denote notes interactively.
# Based on "denote" Emacs package by Protesilaos Stavrou.
# https://protesilaos.com/
# https://github.com/protesilaos/denote

# This script creates new notes with exactly the same filename
# and front matter format as the original Emacs denote.  It does
# not provide the more advanced features of the original, such as
# modifying properties of existing files or creating links.

declare notes_dir="$NOTES_DIR"

make_filename()
{
	# ID
	local filename="$id"

	# Signature: convert signature to lowercase and replace spaces with "="
	if [[ -n $signature ]]; then
		local -l sig="$signature"
		filename+="==${sig// /=}"
	fi

	# Title: convert title to lowercase and replace spaces with "-"
	local -l title="$title"
	filename+="--${title// /-}"

	# Tags: replace spaces with "_"
	local tag
	if [[ -n $tags ]]; then
		filename+="_"
		for tag in "${tags[@]}"; do
			filename+="_${tag}"
		done
	fi

	# File extension: remove "-yaml" or "-toml"
	filename+=".${filetype%-*}"

	echo "$filename"
}

make_txt()
{
	# Format date and tags for txt front matter
	local date tags_txt
	date=$(printf "%(%F)T" "$timestamp")
	tags_txt=$(printf '%s  ' "${tags[@]}")

	# Front matter template for txt
	local front_matter
	front_matter=$(
		cat << EOF
title:      ${title}
date:       ${date}
tags:       ${tags_txt%  }
identifier: ${id}
---------------------------
EOF
	)

	printf "%s\n\n" "$front_matter"
}

make_md()
{
	# Format date and tags for markdown front matter
	# `date` command used instead of `printf` to get a colon in the timezone (%:z)
	local date tags_md
	date=$(date --date="@$timestamp" +"%FT%H:%M:%S%:z")
	if [[ -n $tags ]]; then
		tags_md=$(printf '"%s", ' "${tags[@]}")
		tags_md=${tags_md%, }
	fi

	# Front matter template for markdown-yaml
	local front_matter
	[[ $1 == "yaml" ]] && front_matter=$(
		cat << EOF
---
title:      "${title}"
date:       ${date}
tags:       [${tags_md:-}]
identifier: "${id}"
---
EOF
	)

	# Front matter template for markdown-toml
	[[ $1 == "toml" ]] && front_matter=$(
		cat << EOF
+++
title      = "${title}"
date       = ${date}
tags       = [${tags_md:-}]
identifier = "${id}"
+++
EOF
	)

	printf "%s\n\n" "$front_matter"
}

make_org()
{
	# Format date and tags for org front matter
	local date tags_org
	date=$(printf "%(%F %a %H:%M)T" "$timestamp")
	if [[ -n $tags ]]; then
		tags_org=":"
		tags_org+=$(printf '%s:' "${tags[@]}")
	fi

	# Front matter template for org
	local front_matter
	front_matter=$(
		cat << EOF
#+title:      ${title}
#+date:       [${date}]
#+filetags:   ${tags_org:-}
#+identifier: ${id}
EOF
	)

	printf "%s\n\n" "$front_matter"
}

# Select file type
declare PS3="> "
declare -a filetypes=("txt" "md-yaml" "md-toml" "org")
select item in "${filetypes[@]}"; do
	filetype="$item"
	break
done

# Enter signature
declare signature
read -rp "Signature: " signature

# Enter title
declare title
read -rp "Title: " title

# Enter tags separated by spaces and convert to lowercase
declare -l tags_input
declare -a tags
read -rp "Tags: " tags_input
read -ra tags <<< "$tags_input"

# Generate timestamp for id and front matter date
declare -i timestamp
timestamp=$(printf '%(%s)T')

# Create ID from timestamp
declare id
id=$(printf "%(%Y%m%dT%H%M%S)T" "$timestamp")

# Generate filename and full filepath
declare filename filepath
filename=$(make_filename)
filepath="${notes_dir}/${filename}"

# Show completed front matter and filename
declare filetype
case $filetype in
	"txt")
		echo
		make_txt
		printf "%s\n\n" "$filename"
		;;
	"md-yaml")
		echo
		make_md "yaml"
		printf "%s\n\n" "$filename"
		;;
	"md-toml")
		echo
		make_md "toml"
		printf "%s\n\n" "$filename"
		;;
	"org")
		echo
		make_org
		printf "%s\n\n" "$filename"
		;;
esac

# Request confirmation for creating and editing file
declare -l choice
read -rp "Create and edit file [Y/n] " choice

if [[ ${choice:-"y"} == "y" ]]; then

	# Create file containing front matter
	case $filetype in
		"txt") make_txt > "$filepath" ;;
		"md-yaml") make_md "yaml" > "$filepath" ;;
		"md-toml") make_md "toml" > "$filepath" ;;
		"org") make_org > "$filepath" ;;
	esac

	# Open file in editor of choice
	$EDITOR "$filepath"

else
	exit
fi
