#!/usr/bin/env bash

# Create denote notes interactively.
# Based on "denote" Emacs package by Protesilaos Stavrou.
# https://protesilaos.com/
# https://github.com/protesilaos/denote

# This script creates new notes with exactly the same filename
# and front matter format as the original Emacs denote.  It does
# not provide the more advanced features of the original, such as
# modifying properties of existing files or creating links.

notes_dir="$NOTES_DIR"

make_filename()
{
	# ID
	local filename+="$id"

	# Signature: convert signature to lowercase and replace spaces with "="
	if [[ -n $signature ]]; then
		local sig="${signature,,}"
		filename+="==${sig// /=}"
	fi

	# Title: convert title to lowercase and replace spaces with "-"
	local title=${title,,}
	filename+="--${title// /-}"

	# Tags: replace spaces with "_"
	if [[ -n $tags ]]; then
		filename+="_"
		for tag in "${tags[@]}"; do
			filename+="_${tag}"
		done
	fi

	# File extension: remove "-yaml" or "-toml"
	filename+=".${filetype%-*}"

	echo "$filename"
}

make_txt()
{
	local date
	local tags_txt
	local front_matter

	# Format date and tags for txt front matter
	date=$(date --date="@$timestamp" +%F)
	tags_txt=$(printf '%s  ' "${tags[@]}")

	# Front matter template for txt
	front_matter=$(
		cat << EOF
title:      ${title}
date:       ${date}
tags:       ${tags_txt%  }
identifier: ${id}
---------------------------
EOF
	)

	printf "%s\n\n" "$front_matter"
}

make_md()
{
	local date
	local tags_md
	local front_matter

	# Format date and tags for markdown front matter
	date=$(date --date="@$timestamp" +"%FT%H:%M:%S%:z")
	if [[ -n $tags ]]; then
		tags_md=$(printf '"%s", ' "${tags[@]}")
		tags_md=${tags_md%, }
	fi

	# Front matter template for markdown-yaml
	[[ $1 == "yaml" ]] && front_matter=$(
		cat << EOF
---
title:      "${title}"
date:       ${date}
tags:       [${tags_md:-}]
identifier: "${id}"
---
EOF
	)

	# Front matter template for markdown-toml
	[[ $1 == "toml" ]] && front_matter=$(
		cat << EOF
+++
title      = "${title}"
date       = ${date}
tags       = [${tags_md:-}]
identifier = "${id}"
+++
EOF
	)

	printf "%s\n\n" "$front_matter"
}

make_org()
{
	local date
	local tags_org
	local front_matter

	# Format date and tags for org front matter
	date=$(date --date="@$timestamp" +"%F %a %H:%M")
	if [[ -n $tags ]]; then
		tags_org=":"
		tags_org+=$(printf '%s:' "${tags[@]}")
	fi

	# Front matter template for org
	front_matter=$(
		cat << EOF
#+title:      ${title}
#+date:       [${date}]
#+filetags:   ${tags_org:-}
#+identifier: ${id}
EOF
	)

	printf "%s\n\n" "$front_matter"
}

# Select file type
filetypes=("txt" "md-yaml" "md-toml" "org")
PS3="> "
select item in "${filetypes[@]}"; do
	filetype="$item"
	break
done

# Enter signature
read -rp "Signature: " signature

# Enter title
read -rp "Title: " title

# Enter tags separated by spaces and convert to lowercase
read -rp "Tags: " tags_string
tags=(${tags_string,,})

# Generate timestamp for id and front matter date
timestamp=$(printf '%(%s)T')

# Create ID from timestamp
id=$(date --date="@$timestamp" +"%Y%m%dT%H%M%S")

# Generate filename and full filepath
filename=$(make_filename)
filepath="${notes_dir}/${filename}"

# Show completed front matter and filename
case $filetype in
	"txt")
		echo
		make_txt
		printf "%s\n\n" "$filename"
		;;
	"md-yaml")
		echo
		make_md "yaml"
		printf "%s\n\n" "$filename"
		;;
	"md-toml")
		echo
		make_md "toml"
		printf "%s\n\n" "$filename"
		;;
	"org")
		echo
		make_org
		printf "%s\n\n" "$filename"
		;;
esac

# Request confirmation for creating and editing file
read -rp "Create and edit file? (y/n): " choice

if [[ $choice == "y" ]]; then

	# Create file containing front matter
	case $filetype in
		"txt") make_txt > "$filepath" ;;
		"md-yaml") make_md "yaml" > "$filepath" ;;
		"md-toml") make_md "toml" > "$filepath" ;;
		"org") make_org > "$filepath" ;;
	esac

	# Open file in editor of choice
	$EDITOR "$filepath"

else
	exit
fi
