#!/usr/bin/env bash

purchased_data_file="$FOOD_DATA_DIR/purchased"

new_entry()
{
	local date=$(gum input --value="$(date -I)" --header="Date")
	local date_with_weekday=$(date --date="$date" +"%F %a")
	local food=$(cut --fields=2 $purchased_data_file \
		| sort --unique \
		| gum filter --no-strict)

	echo -e "$date_with_weekday\t$food" >> $purchased_data_file
}

case $1 in
	"e") (cd $FOOD_DATA_DIR && nvim -c FZF) ;;
	"n") new_entry ;;
	"") cat $purchased_data_file ;;
esac
