#!/usr/bin/env bash

# Insert records including details of fuel refills into database.

db=$DB_DIR/auto.db
table=fuel

read -p "Total price: " amount
read -p "Price per gallon: " ppg
read -p "Gallons: " gallons
read -p "Miles per gallon: " mpg
read -p "Odometer: " miles

sqlite3 $db "INSERT INTO $table VALUES (date('now', 'localtime'), $amount, $ppg, $gallons, $mpg, $miles);"

sqlite3 -box $db "SELECT * FROM $table ORDER BY Date DESC LIMIT 5;"
