#!/usr/bin/env bash

# Display and modify daily task tracker log stored in local text files.

data_file="$LOG_DATA_DIR/log_data"
template_file="$LOG_DATA_DIR/log_template"

case $1 in
	"e")
		(cd $LOG_DATA_DIR && nvim -c FZF)
		;;
	"i")
		while IFS= read -r line; do
			echo "$(date +'%Y-%m-%d %a') [ ] ${line}: " >> $data_file
		done < $template_file
		log t
		;;
	"t")
		clear
		grep $(date +%Y-%m-%d) $data_file
		;;
	"")
		cat $data_file
		;;
	*)
		description="${@:2}"
		date="$(date +%Y-%m-%d)"
		sed -i "/${date}.*$1/ s/\[ \]/[X]/" $data_file
		sed -i "/${date}.*$1/ s/$/${description}/" $data_file
		log t
		;;

esac
