#!/usr/bin/env bash

# Disable wireless and remote access services.

sudo systemctl stop syncthing@maf.service
sudo systemctl stop bluetooth.service
sudo systemctl stop sshd.service

sudo ufw deny syncthing
