#!/usr/bin/env bash

# Disable services while away from home.

sudo systemctl stop syncthing@maf.service
sudo systemctl stop bluetooth.service
sudo systemctl stop sshd.service
sudo systemctl stop avahi-daemon
sudo systemctl stop passim
sudo systemctl stop wsdd
