#!/usr/bin/env bash

# Print lists of show episodes from a local database
# and track which episodes have been watched.

# Environment variables:
# SHOWS_DB        - Path of sqlite database containing information on show episodes
# SHOWS_CSV       - Path of csv file used for creating main menu
# SHOWS_MEDIA_DIR - Path of base directory where media files are found

get_episode()
{
	case $1 in
		"next")
			episode_num=$(sqlite3 \
				"$SHOWS_DB" "SELECT NumOverall FROM $table WHERE WatchedDate IS NULL ORDER BY NumOverall LIMIT 1")
			;;
		"random")
			episode_num=$(sqlite3 \
				"$SHOWS_DB" "SELECT NumOverall FROM $table WHERE WatchedDate IS NULL ORDER BY random() LIMIT 1")
			;;
		*)
			episode_num=$(sqlite3 \
				"$SHOWS_DB" "SELECT NumOverall FROM $table WHERE NumOverall == $1")
			;;
	esac

	[[ -n $episode_num ]] || echo "No unwatched episodes" && return
	episode_title=$(sqlite3 "$SHOWS_DB" "SELECT Title FROM $table WHERE NumOverall == $episode_num")
	sqlite3 "$SHOWS_DB" -box "SELECT * FROM $table WHERE NumOverall == $episode_num"

	echo
	[[ $show_media_dir ]] && echo "p. Play episode"
	[[ $episode_num ]] && echo "w. Mark episode $episode_num as watched"
}

actions()
{
	echo
	echo "1) List episodes"
	echo "2) Next episode"
	echo "3) Random episode"
	echo "4) Select episode"
	[[ $table == "xfiles" ]] && echo "a) List mythology arc"
	echo "m) Main menu"
	echo

	while true; do
		read -rp "${title}> " action
		echo
		case $action in
			1)
				sqlite3 "$SHOWS_DB" -box "SELECT * from $table"
				echo
				;;
			2)
				get_episode "next"
				echo
				;;
			3)
				get_episode "random"
				echo
				;;
			4)
				read -rp "Episode: " episode
				get_episode "$episode"
				echo
				;;
			a)
				sqlite3 "$SHOWS_DB" -box "SELECT * FROM $table WHERE Mytharc IS NOT NULL"
				echo
				;;
			p)
				episode_title_formatted=${episode_title//[![:word:]]/}
				episode_filename=$(find "$SHOWS_MEDIA_DIR/$show_media_dir" -type f 2> /dev/null \
					| fzf -i -1 -f "$episode_title_formatted" \
					| head -n 1)
				[[ $? != 0 ]] && echo -e "Media not found\n" && continue
				xdg-open "$episode_filename" 2> /dev/null
				;;
			w)
				sqlite3 "$SHOWS_DB" "UPDATE $table SET WatchedDate = date('now', 'localtime') WHERE NumOverall = $episode_num"
				echo
				continue
				;;
			m)
				break
				;;
		esac
	done
}

# Get data from csv file
while IFS=',' read -r table title show_media_dir; do
	tables+=("$table")
	titles+=("$title")
	show_media_dirs+=("$show_media_dir")
done < "$SHOWS_CSV"

set -o pipefail

# Show main menu
echo
while true; do
	export COLUMNS=1
	PS3=$'\n'"> "
	select item in "${titles[@]}"; do
		index=$((REPLY - 1))
		table=${tables[$index]}
		title=$item
		show_media_dir=${show_media_dirs[$index]}
		break
	done
	actions
done
