#!/usr/bin/env bash

# Print lists of show episodes from a local database
# and track which episodes have been watched.

# Environment variables:
# SHOWS_DB        - Path of sqlite database containing information on show episodes
# SHOWS_CSV       - Path of csv file used for creating main menu
# SHOWS_MEDIA_DIR - Path of base directory where media files are found

get_episode()
{
	local choice=$1
	local table=$2
	local series_media_dir=$3

	declare -gi episode_num
	case $choice in
		"next")
			episode_num=$(sqlite3 \
				"$SHOWS_DB" "SELECT NumOverall FROM $table WHERE WatchedDate IS NULL ORDER BY NumOverall LIMIT 1")
			;;
		"random")
			episode_num=$(sqlite3 \
				"$SHOWS_DB" "SELECT NumOverall FROM $table WHERE WatchedDate IS NULL ORDER BY random() LIMIT 1")
			;;
		*)
			episode_num=$(sqlite3 \
				"$SHOWS_DB" "SELECT NumOverall FROM $table WHERE NumOverall == $choice")
			;;
	esac

	if [[ -z $episode_num ]]; then
		echo "No unwatched episodes"
		return
	fi

	declare -g episode_title
	episode_title=$(sqlite3 "$SHOWS_DB" "SELECT Title FROM $table WHERE NumOverall == $episode_num")
	sqlite3 "$SHOWS_DB" -box "SELECT * FROM $table WHERE NumOverall == $episode_num"
	echo

	[[ -n $series_media_dir ]] && echo "p. Play episode"
	[[ -n $episode_num ]] && echo "w. Mark episode $episode_num as watched"
}

series_menu()
{
	local table=$1
	local series_title=$2
	local series_media_dir=$3

	echo
	echo "1) List episodes"
	echo "2) Next episode"
	echo "3) Random episode"
	echo "4) Select episode"
	[[ $table == "xfiles" ]] && echo "a) List mythology arc"
	echo "m) Main menu"
	echo

	while true; do
		local action
		read -rp "${series_title}> " action
		echo
		case $action in
			1)
				sqlite3 "$SHOWS_DB" -box "SELECT * from $table"
				echo
				;;
			2)
				get_episode "next" "$table" "$series_media_dir"
				echo
				;;
			3)
				get_episode "random" "$table" "$series_media_dir"
				echo
				;;
			4)
				local -i episode
				read -rp "Episode: " episode
				get_episode "$episode" "$table" "$series_media_dir"
				echo
				;;
			a)
				sqlite3 "$SHOWS_DB" -box "SELECT * FROM $table WHERE Mytharc IS NOT NULL"
				echo
				;;
			p)
				local episode_filename
				episode_filename=$(find "$SHOWS_MEDIA_DIR/$series_media_dir" -type f 2> /dev/null \
					| fzf -i -1 -f "${episode_title//[![:word:]]/}" \
					| head -n 1)

				[[ $? != 0 ]] && echo -e "Media not found\n" && continue

				xdg-open "$episode_filename" 2> /dev/null
				;;
			w)
				sqlite3 "$SHOWS_DB" "UPDATE $table SET WatchedDate = date('now', 'localtime') WHERE NumOverall = $episode_num"
				;;
			m)
				break
				;;
		esac
	done
}

main_menu()
{
	while IFS=',' read -r tab ser dir; do
		local -a tables+=("$tab")
		local -a series_titles+=("$ser")
		local -a series_media_dirs+=("$dir")
	done < "$SHOWS_CSV"

	echo
	while true; do

		export COLUMNS=1
		export PS3=$'\n'"> "

		local item
		select item in "${series_titles[@]}"; do
			local -i index=$((REPLY - 1))
			local table=${tables[$index]}
			local series_title=$item
			local series_media_dir=${series_media_dirs[$index]}
			break
		done

		series_menu "$table" "$series_title" "$series_media_dir"

	done
}

set -o pipefail

main_menu
