#!/usr/bin/env bash

data_file_daily="$TASK_DATA_DIR/data_daily"
template_daily="$TASK_DATA_DIR/template_daily"

case $1 in
	"a")
		# task-daily a
		# Show all DAILY tasks
		cat "$data_file_daily"
		;;
	"")
		# task-daily
		# Show current DAILY tasks.  Create new DAILY tasks if none exist.
		date=$(date +%F)
		tasks=$(grep "$date" "$data_file_daily")
		if [[ -z $tasks ]]; then
			while IFS= read -r line; do
				echo "$(date +'%Y-%m-%d %a') [ ] ${line}: " >> "$data_file_daily"
			done < "$template_daily"
			tasks=$(grep "$date" "$data_file_daily")
		fi
		grep "$(date +%F)" "$data_file_daily"
		;;
	*)
		# task-daily [pattern [comment]]
		# Mark task complete and add comment
		description="${*:2}"
		date="$(date +%Y-%m-%d)"
		sed -i "/${date}.*$1/ s/\[ \]/[X]/" "$data_file_daily"
		sed -i "/${date}.*$1/ s/$/${description}/" "$data_file_daily"
		;;
esac
