#!/usr/bin/env bash

data_file_monthly="$TASK_DATA_DIR/data_monthly"
template_monthly="$TASK_DATA_DIR/template_monthly"

case $1 in
	"a")
		# task-monthly a
		# Show all MONTHLY tasks
		cat "$data_file_monthly"
		;;
	"i")
		# task-monthly i
		# Create new MONTHLY tasks from template
		while IFS= read -r line; do
			echo "$(date +'%Y-%m--- ---') [ ] $line" >> "$data_file_monthly"
		done < "$template_monthly"
		;;
	"")
		# task-monthly
		# Show current MONTHLY tasks.  Mark complete if pattern is provided.
		grep "$(date +%Y-%m)" "$data_file_monthly"
		;;
	*)
		# task-monthly [pattern]
		# Mark complete task that matches pattern
		month=$(date +%Y-%m)
		sed -i "/$month.*$1/ s/\[ \]/[X]/" "$data_file_monthly"
		sed -i "/$month.*$1/ s/-- ---/$(date +'%d %a')/" "$data_file_monthly"
		;;
esac
