#!/usr/bin/env bash

data_file_todo="$TASK_DATA_DIR/data_todo"

case $1 in
	"n")
		# task-todo n
		# Create new Todo task interactively
		;;
	"")
		# task-todo
		# Show incomplete Todo tasks
		grep "\[ \]" "$data_file_todo" | sort
		;;
	*)
		# task-todo [pattern]
		# Mark task complete that matches pattern
		sed -i "/$1/ s/\[ \]/[X]/" "$data_file_todo"
		;;
esac
