#!/usr/bin/env bash

data_file_daily="$DATA_DIR/task/data_daily"
template_daily="$DATA_DIR/task/template_daily"

case $1 in
	"a")
		# task-daily a
		# Show all DAILY tasks
		cat "$data_file_daily"
		;;
	"")
		# task-daily
		# Show current DAILY tasks.  Create new DAILY tasks if none exist.
		date=$(printf "%(%F)T" -1)
		mapfile -t tasks < <(grep "$date" "$data_file_daily")

		if [[ -z ${tasks[*]} ]]; then
			while IFS= read -r line; do
				printf "%(%F %a)T [ ] %s: \n" -1 "$line" >> "$data_file_daily"
			done < "$template_daily"
			mapfile -t tasks < <(grep "$date" "$data_file_daily")
		fi

		for task in "${tasks[@]}"; do
			echo "$task"
		done
		;;
	*)
		# task-daily [pattern [comment]]
		# Mark task complete and add comment
		pattern=$1
		comment="${*:2}"
		date=$(printf "%(%F)T" -1)

		sed -i "/${date}.*${pattern}/ s/\[ \]/[X]/" "$data_file_daily"
		sed -i "/${date}.*${pattern}/ s/$/${comment}/" "$data_file_daily"
		;;
esac
