#!/usr/bin/env bash

data_file_monthly="$TASK_DATA_DIR/data_monthly"
template_monthly="$TASK_DATA_DIR/template_monthly"

case $1 in
	"a")
		# task-monthly a
		# Show all MONTHLY tasks
		cat "$data_file_monthly"
		;;
	"")
		# task-monthly
		# Show current MONTHLY tasks.  Create new MONTHLY tasks if none exist.
		date=$(date +"%Y-%m")
		mapfile -t tasks < <(grep "$date" "$data_file_monthly")
		if [[ -z $tasks ]]; then
			while IFS= read -r line; do
				echo "$(date +'%Y-%m--- ---') [ ] $line" >> "$data_file_monthly"
			done < "$template_monthly"
			mapfile -t tasks < <(grep "$date" "$data_file_monthly")
		fi
		for task in "${tasks[@]}"; do
			echo "$task"
		done
		;;
	*)
		# task-monthly [pattern]
		# Mark complete task that matches pattern
		month=$(date +%Y-%m)
		sed -i "/$month.*$1/ s/\[ \]/[X]/" "$data_file_monthly"
		sed -i "/$month.*$1/ s/-- ---/$(date +'%d %a')/" "$data_file_monthly"
		;;
esac
