#!/bin/bash

# Print the contents of /etc/passwd in a more readable, column-aligned format.

awk 'BEGIN {FS=":"}; {printf "%-24s %2s %6s %6s %s %-48s %-30s %-20s\n", $1, $2, $3, $4, "", $5, $6, $7};' /etc/passwd 
