#!/usr/bin/env bash

# Print the contents of /etc/passwd in a column-aligned format.

column --separator ":" \
       --table \
       -N USERNAME,PW,UID,GID,DESCRIPTION,HOME,LOGIN-SHELL \
       -H PW \
       -R UID,GID \
       /etc/passwd
